/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Anamnez.java
 *
 * Created on 28.Ara.2011, 00:07:52
 */
package disciotomasyonu;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author mustafa
 */
public class Anamnez extends javax.swing.JFrame {
 
 ButtonGroup soru1;
    /** Creates new form Anamnez */
    String[] cevap;
    JRadioButton[] evet;
    JRadioButton[] hayır;
    String tc;
    public Anamnez(String tc,int kontrol) {
        this.tc=tc;
        cevap=new String[7];
        evet=new JRadioButton[7];
        hayır=new JRadioButton[7];
        initComponents();
        evet[0]=jRadioButton1;
        evet[1]=jRadioButton4;
        evet[2]=jRadioButton6;
        evet[3]=jRadioButton8;
        evet[4]=jRadioButton10;
        evet[5]=jRadioButton12;
        evet[6]=jRadioButton14;
        
        hayır[0]=jRadioButton2;
        hayır[1]=jRadioButton3;
        hayır[2]=jRadioButton5;
        hayır[3]=jRadioButton7;
        hayır[4]=jRadioButton9;
        hayır[5]=jRadioButton11;
        hayır[6]=jRadioButton13;
        
        
           jRadioButton1.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
           
           cevap[0]=jRadioButton1.getText();
          
          
            }
        });
           jRadioButton2.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
         cevap[0]=jRadioButton2.getText();
            }
        });
           jRadioButton3.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
           cevap[1]=jRadioButton3.getText();
            }
        });
           jRadioButton4.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
           cevap[1]=jRadioButton4.getText();
            }
        });
           jRadioButton5.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
          cevap[2]=jRadioButton5.getText();
            }
        });
           jRadioButton6.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
           cevap[2]=jRadioButton6.getText();
            }
        });
           jRadioButton7.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
           cevap[3]=jRadioButton7.getText();
            }
        });
       jRadioButton8.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
           cevap[3]=jRadioButton8.getText();
            }
        });
       jRadioButton9.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
           cevap[4]=jRadioButton9.getText();
            }
        });
        jRadioButton10.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
           cevap[4]=jRadioButton10.getText();
            }
        });
       jRadioButton11.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
           cevap[5]=jRadioButton11.getText();
            }
        });
       jRadioButton12.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
         cevap[5]=jRadioButton12.getText();
            }
        });
       jRadioButton13.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
         cevap[6]=jRadioButton13.getText();
            }
        });
       jRadioButton14.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
          cevap[6]=jRadioButton14.getText();
            }
        });
      if(kontrol==1) {hastacevap();}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TC:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("AŞAĞIDAKİ SORULARI CEVAPLAYINIZ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel13.setText("1) Son iki yılda hiç hastaneye gittiniz mi?");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel14.setText("2)Son iki yıl içerisinde doktor kontrolunde oldunuz mu?");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel15.setText("3)Son iki yıl içerisinde herhangi bir nedenle ilaç aldınız mı?");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel16.setText("4)  Penisilin,kodein veya bir başka ilaç yada maddeye alerjiniz var mı?");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel17.setText("5)  Tedavi gerektiren aşırı kanamanız oldumu?");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel20.setText("6) Son 4 saat içinde birşey yiyip içtiniz mi?");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel21.setText("7) Müteharrik proteziniz var mı?");

        jRadioButton1.setText("evet");

        jRadioButton2.setText("hayır");

        jRadioButton3.setText("hayır");

        jRadioButton4.setText("evet");

        jRadioButton5.setText("hayır");

        jRadioButton6.setText("evet");

        jRadioButton7.setText("hayır");

        jRadioButton8.setText("evet");

        jRadioButton9.setText("hayır");

        jRadioButton10.setText("evet");

        jRadioButton11.setText("hayır");

        jRadioButton12.setText("evet");

        jRadioButton13.setText("hayır");

        jRadioButton14.setText("evet");

        jButton1.setText("Kaydet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jRadioButton12)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton11))
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton10)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2)))
                        .addContainerGap(132, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jRadioButton14)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(130, 130, 130))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(jLabel13)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton7))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton9))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton12)
                            .addComponent(jRadioButton11))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton14)
                            .addComponent(jRadioButton13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
   
    kaydet();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anamnez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anamnez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anamnez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anamnez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Anamnez("12345678910",0).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void kaydet() {
         String sql=null;
        try {
           
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/disci?useUnicode=true&characterEncoding=UTF-8","root","");
            Statement komut=conn.createStatement();
            for(int i=0;i<cevap.length;i++)
            {
            sql="insert into anamnez_formu values("+null+",'"+tc+"',"+i+",'"+cevap[i]+"')";
            komut.executeUpdate(sql);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Anamnez.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Anamnez.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void hastacevap() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
               Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/disci?useUnicode=true&characterEncoding=UTF-8","root","");
               Statement komut=conn.createStatement();
               ResultSet rs=komut.executeQuery("select * from anamnez_formu where HASTA_TC='"+tc+"'");
               if(rs!=null) jButton1.setVisible(false);
               int i=0;
               while(rs.next())
               {
               if(rs.getString(4).equals("evet"))
               {
               evet[i].setSelected(true);
               }
               else{
               hayır[i].setSelected(true);
               }
               i++;
               }
        } catch (SQLException ex) {
            System.out.println("hata:"+ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Anamnez.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
