/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HastaBilgileri.java
 *
 * Created on 24.Ara.2011, 19:36:15
 */

package disciotomasyonu;

import com.mysql.jdbc.ResultSetMetaData;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mustafa
 */
public class HastaBilgileri extends javax.swing.JFrame {

    /** Creates new form HastaBilgileri */
    int doktorid;
    public HastaBilgileri(int id) {
        this.doktorid=id;
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("disci.jpg"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TC :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Göster");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Çıkış");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        hastaGoster();
    }//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
  this.setVisible(false);
    
}//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HastaBilgileri(1).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void hastaGoster() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/disci?useUnicode=true&characterEncoding=UTF-8", "root", "");
            Statement komut = conn.createStatement();
            String sql = "select ADI,SOYADI,PADI,PSOYADI,ISLEM,TUTAR from hasta_kayit,tedavi,islem2,personel where TCKNO='" + jTextField1.getText() + "' AND ID=HASTA_ID AND ISLEMID=ISLEM_ID AND DOKTOR_ID='" + doktorid + "' AND PID='"+personelID(doktorid)+"'";
            ResultSet rs = komut.executeQuery(sql);
            String[] baslik2={"ADI","SOYADI","DOKTORADI","DOKTORSOYADI","ISLEM","TUTAR"};
            Vector baslik=new Vector();
            for(int i=0;i<baslik2.length;i++)
            {
            baslik.addElement(baslik2[i]);
            }
            ResultSetMetaData meta=(ResultSetMetaData) rs.getMetaData();
            int column=meta.getColumnCount();
            Vector kayitlar=new Vector();
            while(rs.next())
            {
            Vector sutun=new Vector();
            for(int i=1;i<=column;i++)
            {
            sutun.addElement(rs.getString(i));
            }

            kayitlar.addElement(sutun);
            }
            DefaultTableModel dtm=new DefaultTableModel(kayitlar,baslik);
            jTable1.setModel(dtm);


        } catch (SQLException ex) {
            System.out.println("hata:"+ex.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HastaBilgileri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private int personelID(int doktorid) {
        int id=0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/disci?useUnicode=true&characterEncoding=UTF-8", "root", "");
            Statement komut = conn.createStatement();
            String sql="select PID from doktor,personel where DOKTOR_ID='"+doktorid+"' AND PID=PERSONEL_ID";
            ResultSet rs=komut.executeQuery(sql);
            rs.next();
            id=rs.getInt(1);
        } catch (SQLException ex) {
            Logger.getLogger(HastaBilgileri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HastaBilgileri.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }

}
