/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * hastaBilgileriSekreter.java
 *
 * Created on 24.Ara.2011, 20:31:34
 */

package disciotomasyonu;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.ResultSetMetaData;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mustafa
 */
public class hastaBilgileriSekreter extends javax.swing.JFrame {

    /** Creates new form hastaBilgileriSekreter */
    DefaultComboBoxModel model=new DefaultComboBoxModel();
    public hastaBilgileriSekreter() {
        try {
            this.setIconImage(Toolkit.getDefaultToolkit().getImage("disci.jpg"));
            initComponents();
            setLocation(300, 200);
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/merve", "root", "");
            Statement komut = conn.createStatement();
            ResultSet rs = komut.executeQuery("select PADI,PSOYADI from personel where UNVAN = 'doktor'");
            while (rs.next()) {
                model.addElement(rs.getString(1) + " " + rs.getString(2));
            }
        } catch (SQLException ex) {
            System.out.println("hata:"+ex.getMessage());
        } catch (ClassNotFoundException ex) {
            System.out.println("hata:"+ex.getMessage());
        }
        jComboBox1.setModel(model);
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TC :");

        jButton1.setText("Göster");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Çıkış");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(32, 32, 32)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        hastaGoster();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Sekreter().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hastaBilgileriSekreter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void hastaGoster() {
    try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/merve", "root", "");
            Statement komut = conn.createStatement();
            String sql = "select ADI,SOYADI,PADI,PSOYADI,ISLEM,TUTAR from hasta_kayit,tedavi,islem2,personel where TCKNO='" + jTextField1.getText() + "' AND ID=HASTA_ID AND ISLEMID=ISLEM_ID AND DOKTOR_ID='" +(jComboBox1.getSelectedIndex()+1)+ "' AND PID='"+personelID(jComboBox1.getSelectedIndex()+1)+"'";
            ResultSet rs = komut.executeQuery(sql);
            String[] baslik2={"ADI","SOYADI","DOKTORADI","DOKTORSOYADI","ISLEM","TUTAR"};
            Vector baslik=new Vector();
            for(int i=0;i<baslik2.length;i++)
            {
            baslik.addElement(baslik2[i]);
            }
            ResultSetMetaData meta=(ResultSetMetaData) rs.getMetaData();
            int column=meta.getColumnCount();
            Vector kayitlar=new Vector();
            while(rs.next())
            {
            Vector sutun=new Vector();
            for(int i=1;i<=column;i++)
            {
            sutun.addElement(rs.getString(i));
            }

            kayitlar.addElement(sutun);
            }
            DefaultTableModel dtm=new DefaultTableModel(kayitlar,baslik);
            jTable1.setModel(dtm);


        } catch (SQLException ex) {
            System.out.println("hata:"+ex.getMessage());
        } catch (ClassNotFoundException ex) {
            System.out.println("hata:"+ex.getMessage());
        }
    }

    private int personelID(int doktorid) {
        int id=0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/merve", "root", "");
            Statement komut = conn.createStatement();
            String sql="select PID from doktor,personel where DOKTOR_ID='"+doktorid+"' AND PID=PERSONEL_ID";
            ResultSet rs=komut.executeQuery(sql);
            rs.next();
            id=rs.getInt(1);
        } catch (SQLException ex) {
            System.out.println("hata:"+ex.getMessage());
        } catch (ClassNotFoundException ex) {
            System.out.println("hata:"+ex.getMessage());
        }
        return id;
    }

}
