/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Anket.java
 *
 * Created on 11.Ara.2011, 14:48:03
 */
package desktopapplication3;

/**

 */
public class Anket extends javax.swing.JFrame {

    /** Creates new form Anket */
    public Anket() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soru1Secenek = new javax.swing.ButtonGroup();
        soru2Secenek = new javax.swing.ButtonGroup();
        soru3Secenek = new javax.swing.ButtonGroup();
        soru4Secenek = new javax.swing.ButtonGroup();
        soru5Secenek = new javax.swing.ButtonGroup();
        soru6Secenek = new javax.swing.ButtonGroup();
        soru8Secenek = new javax.swing.ButtonGroup();
        soru9Secenek = new javax.swing.ButtonGroup();
        soru10Secenek = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tarihAlani = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel11 = new javax.swing.JLabel();
        soru1 = new javax.swing.JLabel();
        soru1evet = new javax.swing.JRadioButton();
        soru1hayır = new javax.swing.JRadioButton();
        soru2 = new javax.swing.JLabel();
        soru2evet = new javax.swing.JRadioButton();
        soru2hayır = new javax.swing.JRadioButton();
        soru3 = new javax.swing.JLabel();
        soru3evet = new javax.swing.JRadioButton();
        soru3hayır = new javax.swing.JRadioButton();
        soru4 = new javax.swing.JLabel();
        soru4evet = new javax.swing.JRadioButton();
        soru4hayır = new javax.swing.JRadioButton();
        soru5 = new javax.swing.JLabel();
        soru5evet = new javax.swing.JRadioButton();
        soru5hayır = new javax.swing.JRadioButton();
        soru6 = new javax.swing.JLabel();
        soru6evet = new javax.swing.JRadioButton();
        soru6hayır = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        soru7 = new javax.swing.JLabel();
        isimAlani = new javax.swing.JTextField();
        adresAlani = new javax.swing.JTextField();
        telNoAlani = new javax.swing.JTextField();
        dogumtarihiAlani = new javax.swing.JTextField();
        kiloAlani = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        boyAlani = new javax.swing.JTextField();
        medeniDurumAlani = new javax.swing.JTextField();
        akrabaTelAlani = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        akrabaAdresAlani = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        kalpProblemi = new javax.swing.JCheckBox();
        sarilik = new javax.swing.JCheckBox();
        anemi = new javax.swing.JCheckBox();
        kalpteUfurum = new javax.swing.JCheckBox();
        romatizma = new javax.swing.JCheckBox();
        sinusProblemi = new javax.swing.JCheckBox();
        hepatit = new javax.swing.JCheckBox();
        diyabet = new javax.swing.JCheckBox();
        tuberkiloz = new javax.swing.JCheckBox();
        astim = new javax.swing.JCheckBox();
        epilepsi = new javax.swing.JCheckBox();
        artirit = new javax.swing.JCheckBox();
        soru8 = new javax.swing.JLabel();
        soru8evet = new javax.swing.JRadioButton();
        soru8hayır = new javax.swing.JRadioButton();
        soru9 = new javax.swing.JLabel();
        soru9evet = new javax.swing.JRadioButton();
        soru9hayır = new javax.swing.JRadioButton();
        soru10 = new javax.swing.JLabel();
        soru10evet = new javax.swing.JRadioButton();
        soru10hayır = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jPanel1.background")); // NOI18N
        jPanel1.setBorder(new javax.swing.border.LineBorder(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jPanel1.border.lineColor"), 3, true)); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        tarihAlani.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jTextField9.font")); // NOI18N
        tarihAlani.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("tarihAlani.text")); // NOI18N
        tarihAlani.setName("tarihAlani"); // NOI18N

        jLabel3.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel2.font")); // NOI18N
        jLabel3.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel2.font")); // NOI18N
        jLabel4.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel2.font")); // NOI18N
        jLabel5.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel2.font")); // NOI18N
        jLabel6.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel2.font")); // NOI18N
        jLabel7.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel9.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel2.font")); // NOI18N
        jLabel9.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel2.font")); // NOI18N
        jLabel10.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jDesktopPane1.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jDesktopPane1.background")); // NOI18N
        jDesktopPane1.setName("jDesktopPane1"); // NOI18N

        jLabel11.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel11.font")); // NOI18N
        jLabel11.setForeground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jLabel1.foreground")); // NOI18N
        jLabel11.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        jLabel11.setBounds(20, 0, 300, 19);
        jDesktopPane1.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru1.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel17.font")); // NOI18N
        soru1.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru1.text")); // NOI18N
        soru1.setName("soru1"); // NOI18N
        soru1.setBounds(20, 40, 270, 14);
        jDesktopPane1.add(soru1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru1evet.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru1Secenek.add(soru1evet);
        soru1evet.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru1evet.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru1evet.text")); // NOI18N
        soru1evet.setName("soru1evet"); // NOI18N
        soru1evet.setBounds(30, 60, 60, 23);
        jDesktopPane1.add(soru1evet, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru1hayır.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru1Secenek.add(soru1hayır);
        soru1hayır.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru1hayır.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru1hayır.text")); // NOI18N
        soru1hayır.setName("soru1hayır"); // NOI18N
        soru1hayır.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soru1hayırActionPerformed(evt);
            }
        });
        soru1hayır.setBounds(130, 60, 60, 23);
        jDesktopPane1.add(soru1hayır, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru2.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel17.font")); // NOI18N
        soru2.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru2.text")); // NOI18N
        soru2.setName("soru2"); // NOI18N
        soru2.setBounds(20, 90, 320, 14);
        jDesktopPane1.add(soru2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru2evet.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru2Secenek.add(soru2evet);
        soru2evet.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru2evet.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru2evet.text")); // NOI18N
        soru2evet.setName("soru2evet"); // NOI18N
        soru2evet.setBounds(30, 110, 70, 23);
        jDesktopPane1.add(soru2evet, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru2hayır.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru2Secenek.add(soru2hayır);
        soru2hayır.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru2hayır.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru2hayır.text")); // NOI18N
        soru2hayır.setName("soru2hayır"); // NOI18N
        soru2hayır.setBounds(130, 110, 55, 23);
        jDesktopPane1.add(soru2hayır, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru3.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel17.font")); // NOI18N
        soru3.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru3.text")); // NOI18N
        soru3.setName("soru3"); // NOI18N
        soru3.setBounds(20, 140, 310, 14);
        jDesktopPane1.add(soru3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru3evet.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru3Secenek.add(soru3evet);
        soru3evet.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru3evet.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru3evet.text")); // NOI18N
        soru3evet.setName("soru3evet"); // NOI18N
        soru3evet.setBounds(30, 160, 60, 23);
        jDesktopPane1.add(soru3evet, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru3hayır.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru3Secenek.add(soru3hayır);
        soru3hayır.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru3hayır.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru3hayır.text")); // NOI18N
        soru3hayır.setName("soru3hayır"); // NOI18N
        soru3hayır.setBounds(130, 160, 55, 23);
        jDesktopPane1.add(soru3hayır, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru4.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel17.font")); // NOI18N
        soru4.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru4.text")); // NOI18N
        soru4.setName("soru4"); // NOI18N
        soru4.setBounds(20, 190, 400, 14);
        jDesktopPane1.add(soru4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru4evet.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru4Secenek.add(soru4evet);
        soru4evet.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru4evet.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru4evet.text")); // NOI18N
        soru4evet.setName("soru4evet"); // NOI18N
        soru4evet.setBounds(30, 210, 60, 23);
        jDesktopPane1.add(soru4evet, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru4hayır.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru4Secenek.add(soru4hayır);
        soru4hayır.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru4hayır.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru4hayır.text")); // NOI18N
        soru4hayır.setName("soru4hayır"); // NOI18N
        soru4hayır.setBounds(130, 210, 55, 23);
        jDesktopPane1.add(soru4hayır, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru5.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel17.font")); // NOI18N
        soru5.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru5.text")); // NOI18N
        soru5.setName("soru5"); // NOI18N
        soru5.setBounds(20, 240, 290, 14);
        jDesktopPane1.add(soru5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru5evet.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru5Secenek.add(soru5evet);
        soru5evet.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru5evet.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru5evet.text")); // NOI18N
        soru5evet.setName("soru5evet"); // NOI18N
        soru5evet.setBounds(30, 260, 51, 23);
        jDesktopPane1.add(soru5evet, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru5hayır.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru5Secenek.add(soru5hayır);
        soru5hayır.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("soru5hayır.font")); // NOI18N
        soru5hayır.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru5hayır.text")); // NOI18N
        soru5hayır.setName("soru5hayır"); // NOI18N
        soru5hayır.setBounds(130, 260, 55, 23);
        jDesktopPane1.add(soru5hayır, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru6.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("soru6.font")); // NOI18N
        soru6.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru6.text")); // NOI18N
        soru6.setName("soru6"); // NOI18N
        soru6.setBounds(20, 290, 220, 14);
        jDesktopPane1.add(soru6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru6evet.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru6Secenek.add(soru6evet);
        soru6evet.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru6evet.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru6evet.text")); // NOI18N
        soru6evet.setName("soru6evet"); // NOI18N
        soru6evet.setBounds(30, 310, 51, 23);
        jDesktopPane1.add(soru6evet, javax.swing.JLayeredPane.DEFAULT_LAYER);

        soru6hayır.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru6Secenek.add(soru6hayır);
        soru6hayır.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru6hayır.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru6hayır.text")); // NOI18N
        soru6hayır.setName("soru6hayır"); // NOI18N
        soru6hayır.setBounds(130, 310, 55, 23);
        jDesktopPane1.add(soru6hayır, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jPanel2.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        soru7.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel17.font")); // NOI18N
        soru7.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru7.text")); // NOI18N
        soru7.setName("soru7"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(soru7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(678, Short.MAX_VALUE)
                .addComponent(soru7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        jScrollPane1.setViewportView(jPanel2);

        jScrollPane1.setBounds(0, -338, 760, 810);
        jDesktopPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        isimAlani.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jTextField9.font")); // NOI18N
        isimAlani.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("isimAlani.text")); // NOI18N
        isimAlani.setName("isimAlani"); // NOI18N

        adresAlani.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jTextField9.font")); // NOI18N
        adresAlani.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("adresAlani.text")); // NOI18N
        adresAlani.setName("adresAlani"); // NOI18N

        telNoAlani.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jTextField9.font")); // NOI18N
        telNoAlani.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("telNoAlani.text")); // NOI18N
        telNoAlani.setName("telNoAlani"); // NOI18N

        dogumtarihiAlani.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jTextField9.font")); // NOI18N
        dogumtarihiAlani.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("dogumtarihiAlani.text")); // NOI18N
        dogumtarihiAlani.setName("dogumtarihiAlani"); // NOI18N

        kiloAlani.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jTextField9.font")); // NOI18N
        kiloAlani.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("kiloAlani.text")); // NOI18N
        kiloAlani.setName("kiloAlani"); // NOI18N

        jLabel8.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel8.font")); // NOI18N
        jLabel8.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        boyAlani.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jTextField9.font")); // NOI18N
        boyAlani.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("boyAlani.text")); // NOI18N
        boyAlani.setName("boyAlani"); // NOI18N

        medeniDurumAlani.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jTextField9.font")); // NOI18N
        medeniDurumAlani.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("medeniDurumAlani.text")); // NOI18N
        medeniDurumAlani.setName("medeniDurumAlani"); // NOI18N

        akrabaTelAlani.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("akrabaTelAlani.font")); // NOI18N
        akrabaTelAlani.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("akrabaTelAlani.text")); // NOI18N
        akrabaTelAlani.setName("akrabaTelAlani"); // NOI18N

        jLabel22.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel22.font")); // NOI18N
        jLabel22.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        akrabaAdresAlani.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jTextField9.font")); // NOI18N
        akrabaAdresAlani.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("akrabaAdresAlani.text")); // NOI18N
        akrabaAdresAlani.setName("akrabaAdresAlani"); // NOI18N

        jSeparator1.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        jSeparator1.setAlignmentX(2.5F);
        jSeparator1.setName("jSeparator1"); // NOI18N

        kalpProblemi.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        kalpProblemi.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        kalpProblemi.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("kalpProblemi.text")); // NOI18N
        kalpProblemi.setName("kalpProblemi"); // NOI18N

        sarilik.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        sarilik.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        sarilik.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("sarilik.text")); // NOI18N
        sarilik.setName("sarilik"); // NOI18N

        anemi.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        anemi.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        anemi.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("anemi.text")); // NOI18N
        anemi.setName("anemi"); // NOI18N

        kalpteUfurum.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        kalpteUfurum.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        kalpteUfurum.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("kalpteUfurum.text")); // NOI18N
        kalpteUfurum.setName("kalpteUfurum"); // NOI18N

        romatizma.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        romatizma.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        romatizma.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("romatizma.text")); // NOI18N
        romatizma.setName("romatizma"); // NOI18N

        sinusProblemi.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        sinusProblemi.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        sinusProblemi.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("sinusProblemi.text")); // NOI18N
        sinusProblemi.setName("sinusProblemi"); // NOI18N

        hepatit.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        hepatit.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        hepatit.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("hepatit.text")); // NOI18N
        hepatit.setName("hepatit"); // NOI18N

        diyabet.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        diyabet.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        diyabet.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("diyabet.text")); // NOI18N
        diyabet.setName("diyabet"); // NOI18N

        tuberkiloz.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        tuberkiloz.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        tuberkiloz.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("tuberkiloz.text")); // NOI18N
        tuberkiloz.setName("tuberkiloz"); // NOI18N

        astim.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        astim.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        astim.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("astim.text")); // NOI18N
        astim.setName("astim"); // NOI18N

        epilepsi.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        epilepsi.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        epilepsi.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("epilepsi.text")); // NOI18N
        epilepsi.setName("epilepsi"); // NOI18N

        artirit.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("diyabet.background")); // NOI18N
        artirit.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        artirit.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("artirit.text")); // NOI18N
        artirit.setName("artirit"); // NOI18N

        soru8.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel17.font")); // NOI18N
        soru8.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru8.text")); // NOI18N
        soru8.setName("soru8"); // NOI18N

        soru8evet.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru8Secenek.add(soru8evet);
        soru8evet.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru8evet.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru8evet.text")); // NOI18N
        soru8evet.setName("soru8evet"); // NOI18N

        soru8hayır.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru8Secenek.add(soru8hayır);
        soru8hayır.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru8hayır.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru8hayır.text")); // NOI18N
        soru8hayır.setName("soru8hayır"); // NOI18N

        soru9.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel17.font")); // NOI18N
        soru9.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru9.text")); // NOI18N
        soru9.setName("soru9"); // NOI18N

        soru9evet.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru9Secenek.add(soru9evet);
        soru9evet.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru9evet.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru9evet.text")); // NOI18N
        soru9evet.setName("soru9evet"); // NOI18N

        soru9hayır.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru9Secenek.add(soru9hayır);
        soru9hayır.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru9hayır.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru9hayır.text")); // NOI18N
        soru9hayır.setName("soru9hayır"); // NOI18N

        soru10.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jLabel17.font")); // NOI18N
        soru10.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru10.text")); // NOI18N
        soru10.setName("soru10"); // NOI18N

        soru10evet.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru10Secenek.add(soru10evet);
        soru10evet.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru10evet.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru10evet.text")); // NOI18N
        soru10evet.setName("soru10evet"); // NOI18N

        soru10hayır.setBackground(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getColor("jRadioButton4.background")); // NOI18N
        soru10Secenek.add(soru10hayır);
        soru10hayır.setFont(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getFont("jRadioButton10.font")); // NOI18N
        soru10hayır.setText(org.jdesktop.application.Application.getInstance(desktopapplication3.DesktopApplication3.class).getContext().getResourceMap(Anket.class).getString("soru10hayır.text")); // NOI18N
        soru10hayır.setName("soru10hayır"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tarihAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(akrabaTelAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                    .addComponent(medeniDurumAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                    .addComponent(isimAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                    .addComponent(adresAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                    .addComponent(telNoAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                    .addComponent(dogumtarihiAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(kiloAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(boyAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(akrabaAdresAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))))
                        .addContainerGap(213, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(kalpteUfurum, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kalpProblemi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(romatizma)
                    .addComponent(sinusProblemi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sarilik)
                    .addComponent(hepatit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diyabet)
                    .addComponent(tuberkiloz))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(artirit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(epilepsi)
                    .addComponent(astim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anemi))
                .addContainerGap(357, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(soru10evet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(soru10hayır))
                    .addComponent(soru10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(soru9evet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(soru9hayır, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(soru9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(soru8evet, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(soru8hayır, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(soru8, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(443, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tarihAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(isimAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(telNoAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dogumtarihiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kiloAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boyAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(medeniDurumAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(akrabaTelAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(akrabaAdresAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kalpProblemi)
                    .addComponent(sarilik)
                    .addComponent(anemi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kalpteUfurum)
                    .addComponent(hepatit)
                    .addComponent(astim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(romatizma)
                    .addComponent(diyabet)
                    .addComponent(epilepsi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sinusProblemi)
                    .addComponent(tuberkiloz)
                    .addComponent(artirit))
                .addGap(18, 18, 18)
                .addComponent(soru8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soru8evet)
                    .addComponent(soru8hayır))
                .addGap(18, 18, 18)
                .addComponent(soru9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soru9evet)
                    .addComponent(soru9hayır))
                .addGap(18, 18, 18)
                .addComponent(soru10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soru10evet)
                    .addComponent(soru10hayır))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void soru1hayırActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soru1hayırActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soru1hayırActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Anket().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresAlani;
    private javax.swing.JTextField akrabaAdresAlani;
    private javax.swing.JTextField akrabaTelAlani;
    private javax.swing.JCheckBox anemi;
    private javax.swing.JCheckBox artirit;
    private javax.swing.JCheckBox astim;
    private javax.swing.JTextField boyAlani;
    private javax.swing.JCheckBox diyabet;
    private javax.swing.JTextField dogumtarihiAlani;
    private javax.swing.JCheckBox epilepsi;
    private javax.swing.JCheckBox hepatit;
    private javax.swing.JTextField isimAlani;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox kalpProblemi;
    private javax.swing.JCheckBox kalpteUfurum;
    private javax.swing.JTextField kiloAlani;
    private javax.swing.JTextField medeniDurumAlani;
    private javax.swing.JCheckBox romatizma;
    private javax.swing.JCheckBox sarilik;
    private javax.swing.JCheckBox sinusProblemi;
    private javax.swing.JLabel soru1;
    private javax.swing.JLabel soru10;
    private javax.swing.ButtonGroup soru10Secenek;
    private javax.swing.JRadioButton soru10evet;
    private javax.swing.JRadioButton soru10hayır;
    private javax.swing.ButtonGroup soru1Secenek;
    private javax.swing.JRadioButton soru1evet;
    private javax.swing.JRadioButton soru1hayır;
    private javax.swing.JLabel soru2;
    private javax.swing.ButtonGroup soru2Secenek;
    private javax.swing.JRadioButton soru2evet;
    private javax.swing.JRadioButton soru2hayır;
    private javax.swing.JLabel soru3;
    private javax.swing.ButtonGroup soru3Secenek;
    private javax.swing.JRadioButton soru3evet;
    private javax.swing.JRadioButton soru3hayır;
    private javax.swing.JLabel soru4;
    private javax.swing.ButtonGroup soru4Secenek;
    private javax.swing.JRadioButton soru4evet;
    private javax.swing.JRadioButton soru4hayır;
    private javax.swing.JLabel soru5;
    private javax.swing.ButtonGroup soru5Secenek;
    private javax.swing.JRadioButton soru5evet;
    private javax.swing.JRadioButton soru5hayır;
    private javax.swing.JLabel soru6;
    private javax.swing.ButtonGroup soru6Secenek;
    private javax.swing.JRadioButton soru6evet;
    private javax.swing.JRadioButton soru6hayır;
    private javax.swing.JLabel soru7;
    private javax.swing.JLabel soru8;
    private javax.swing.ButtonGroup soru8Secenek;
    private javax.swing.JRadioButton soru8evet;
    private javax.swing.JRadioButton soru8hayır;
    private javax.swing.JLabel soru9;
    private javax.swing.ButtonGroup soru9Secenek;
    private javax.swing.JRadioButton soru9evet;
    private javax.swing.JRadioButton soru9hayır;
    private javax.swing.JTextField tarihAlani;
    private javax.swing.JTextField telNoAlani;
    private javax.swing.JCheckBox tuberkiloz;
    // End of variables declaration//GEN-END:variables
}
