/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 22.Ara.2011, 01:20:18
 */
package desktopapplication4;

/**
 *
 * @author HP
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tarihalanı = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        isimalanı = new javax.swing.JTextField();
        adresalanı = new javax.swing.JTextField();
        telno = new javax.swing.JTextField();
        doğumtarihialanı = new javax.swing.JTextField();
        kiloalanı = new javax.swing.JTextField();
        boyalanı = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        medenidurumalanı = new javax.swing.JTextField();
        akrabaadresalanı = new javax.swing.JTextField();
        yakınakrabatelalanı = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        kalpproblemi = new javax.swing.JCheckBox();
        sarılık = new javax.swing.JCheckBox();
        anemi = new javax.swing.JCheckBox();
        kalpteüfürüm = new javax.swing.JCheckBox();
        hepatit = new javax.swing.JCheckBox();
        astım = new javax.swing.JCheckBox();
        romatizma = new javax.swing.JCheckBox();
        diyabet = new javax.swing.JCheckBox();
        artrit = new javax.swing.JCheckBox();
        sinüsproblemi = new javax.swing.JCheckBox();
        tüberkiloz = new javax.swing.JCheckBox();
        epilepsi = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(desktopapplication4.DesktopApplication4.class).getContext().getResourceMap(NewJFrame.class);
        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        tarihalanı.setText(resourceMap.getString("tarihalanı.text")); // NOI18N
        tarihalanı.setName("tarihalanı"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        isimalanı.setText(resourceMap.getString("isimalanı.text")); // NOI18N
        isimalanı.setName("isimalanı"); // NOI18N

        adresalanı.setText(resourceMap.getString("adresalanı.text")); // NOI18N
        adresalanı.setName("adresalanı"); // NOI18N

        telno.setText(resourceMap.getString("telno.text")); // NOI18N
        telno.setName("telno"); // NOI18N

        doğumtarihialanı.setText(resourceMap.getString("doğumtarihialanı.text")); // NOI18N
        doğumtarihialanı.setName("doğumtarihialanı"); // NOI18N

        kiloalanı.setText(resourceMap.getString("kiloalanı.text")); // NOI18N
        kiloalanı.setName("kiloalanı"); // NOI18N

        boyalanı.setText(resourceMap.getString("boyalanı.text")); // NOI18N
        boyalanı.setName("boyalanı"); // NOI18N

        jLabel11.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        medenidurumalanı.setText(resourceMap.getString("medenidurumalanı.text")); // NOI18N
        medenidurumalanı.setName("medenidurumalanı"); // NOI18N

        akrabaadresalanı.setText(resourceMap.getString("akrabaadresalanı.text")); // NOI18N
        akrabaadresalanı.setName("akrabaadresalanı"); // NOI18N

        yakınakrabatelalanı.setText(resourceMap.getString("yakınakrabatelalanı.text")); // NOI18N
        yakınakrabatelalanı.setName("yakınakrabatelalanı"); // NOI18N

        jLabel12.setFont(resourceMap.getFont("jLabel12.font")); // NOI18N
        jLabel12.setForeground(resourceMap.getColor("jLabel12.foreground")); // NOI18N
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jRadioButton1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton1.setText(resourceMap.getString("jRadioButton1.text")); // NOI18N
        jRadioButton1.setName("jRadioButton1"); // NOI18N

        jRadioButton2.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton2.setText(resourceMap.getString("jRadioButton2.text")); // NOI18N
        jRadioButton2.setName("jRadioButton2"); // NOI18N

        jLabel14.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        jRadioButton3.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton3.setLabel(resourceMap.getString("jRadioButton3.label")); // NOI18N
        jRadioButton3.setName("jRadioButton3"); // NOI18N

        jRadioButton4.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton4.setLabel(resourceMap.getString("jRadioButton4.label")); // NOI18N
        jRadioButton4.setName("jRadioButton4"); // NOI18N

        jLabel15.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        jRadioButton5.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton5.setText(resourceMap.getString("jRadioButton5.text")); // NOI18N
        jRadioButton5.setName("jRadioButton5"); // NOI18N

        jRadioButton6.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton6.setText(resourceMap.getString("jRadioButton6.text")); // NOI18N
        jRadioButton6.setName("jRadioButton6"); // NOI18N

        jLabel16.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jRadioButton7.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup6.add(jRadioButton7);
        jRadioButton7.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton7.setText(resourceMap.getString("jRadioButton7.text")); // NOI18N
        jRadioButton7.setName("jRadioButton7"); // NOI18N

        jRadioButton8.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup6.add(jRadioButton8);
        jRadioButton8.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton8.setText(resourceMap.getString("jRadioButton8.text")); // NOI18N
        jRadioButton8.setName("jRadioButton8"); // NOI18N

        jLabel17.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jRadioButton9.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup4.add(jRadioButton9);
        jRadioButton9.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton9.setText(resourceMap.getString("jRadioButton9.text")); // NOI18N
        jRadioButton9.setName("jRadioButton9"); // NOI18N

        jRadioButton10.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup4.add(jRadioButton10);
        jRadioButton10.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton10.setText(resourceMap.getString("jRadioButton10.text")); // NOI18N
        jRadioButton10.setName("jRadioButton10"); // NOI18N

        jLabel18.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        jRadioButton11.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup5.add(jRadioButton11);
        jRadioButton11.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton11.setText(resourceMap.getString("jRadioButton11.text")); // NOI18N
        jRadioButton11.setName("jRadioButton11"); // NOI18N

        jRadioButton12.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup5.add(jRadioButton12);
        jRadioButton12.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton12.setText(resourceMap.getString("jRadioButton12.text")); // NOI18N
        jRadioButton12.setName("jRadioButton12"); // NOI18N

        jLabel19.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        kalpproblemi.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        kalpproblemi.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        kalpproblemi.setLabel(resourceMap.getString("kalpproblemi.label")); // NOI18N
        kalpproblemi.setName(""); // NOI18N

        sarılık.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        sarılık.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        sarılık.setText(resourceMap.getString("sarılık.text")); // NOI18N
        sarılık.setName("sarılık"); // NOI18N

        anemi.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        anemi.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        anemi.setText(resourceMap.getString("anemi.text")); // NOI18N
        anemi.setName("anemi"); // NOI18N

        kalpteüfürüm.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        kalpteüfürüm.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        kalpteüfürüm.setText(resourceMap.getString("kalpteüfürüm.text")); // NOI18N
        kalpteüfürüm.setName("kalpteüfürüm"); // NOI18N

        hepatit.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        hepatit.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        hepatit.setText(resourceMap.getString("hepatit.text")); // NOI18N
        hepatit.setName("hepatit"); // NOI18N

        astım.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        astım.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        astım.setText(resourceMap.getString("astım.text")); // NOI18N
        astım.setName("astım"); // NOI18N

        romatizma.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        romatizma.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        romatizma.setText(resourceMap.getString("romatizma.text")); // NOI18N
        romatizma.setName("romatizma"); // NOI18N

        diyabet.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        diyabet.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        diyabet.setText(resourceMap.getString("diyabet.text")); // NOI18N
        diyabet.setName("diyabet"); // NOI18N

        artrit.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        artrit.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        artrit.setText(resourceMap.getString("artrit.text")); // NOI18N
        artrit.setName("artrit"); // NOI18N

        sinüsproblemi.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        sinüsproblemi.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        sinüsproblemi.setText(resourceMap.getString("sinüsproblemi.text")); // NOI18N
        sinüsproblemi.setName("sinüsproblemi"); // NOI18N

        tüberkiloz.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        tüberkiloz.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        tüberkiloz.setText(resourceMap.getString("tüberkiloz.text")); // NOI18N
        tüberkiloz.setName("tüberkiloz"); // NOI18N

        epilepsi.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        epilepsi.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        epilepsi.setText(resourceMap.getString("epilepsi.text")); // NOI18N
        epilepsi.setName("epilepsi"); // NOI18N

        jLabel20.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        jRadioButton13.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup7.add(jRadioButton13);
        jRadioButton13.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton13.setText(resourceMap.getString("jRadioButton13.text")); // NOI18N
        jRadioButton13.setName("jRadioButton13"); // NOI18N

        jRadioButton14.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup7.add(jRadioButton14);
        jRadioButton14.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton14.setText(resourceMap.getString("jRadioButton14.text")); // NOI18N
        jRadioButton14.setName("jRadioButton14"); // NOI18N

        jLabel21.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        jRadioButton15.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup8.add(jRadioButton15);
        jRadioButton15.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton15.setText(resourceMap.getString("jRadioButton15.text")); // NOI18N
        jRadioButton15.setName("jRadioButton15"); // NOI18N

        jRadioButton16.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup8.add(jRadioButton16);
        jRadioButton16.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton16.setText(resourceMap.getString("jRadioButton16.text")); // NOI18N
        jRadioButton16.setName("jRadioButton16"); // NOI18N

        jLabel22.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        jRadioButton17.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup9.add(jRadioButton17);
        jRadioButton17.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton17.setText(resourceMap.getString("jRadioButton17.text")); // NOI18N
        jRadioButton17.setName("jRadioButton17"); // NOI18N

        jRadioButton18.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        buttonGroup9.add(jRadioButton18);
        jRadioButton18.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jRadioButton18.setText(resourceMap.getString("jRadioButton18.text")); // NOI18N
        jRadioButton18.setName("jRadioButton18"); // NOI18N

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jRadioButton5)
                                            .addGap(56, 56, 56)
                                            .addComponent(jRadioButton6))
                                        .addComponent(jLabel16)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(jRadioButton7)
                                            .addGap(55, 55, 55)
                                            .addComponent(jRadioButton8))
                                        .addComponent(jLabel17)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(23, 23, 23)
                                            .addComponent(jRadioButton9))
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel22)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jRadioButton17)
                                            .addGap(48, 48, 48)
                                            .addComponent(jRadioButton18)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                                            .addComponent(jButton1)
                                            .addGap(87, 87, 87))
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel19)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(23, 23, 23)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jRadioButton3)
                                                .addComponent(jRadioButton11))
                                            .addGap(7, 7, 7)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(47, 47, 47)
                                                    .addComponent(jRadioButton4))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(43, 43, 43)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jRadioButton12)
                                                        .addComponent(jRadioButton10)))))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jRadioButton15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRadioButton16))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jRadioButton13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRadioButton14))
                                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(sinüsproblemi)
                                                .addComponent(romatizma)
                                                .addComponent(kalpteüfürüm)
                                                .addComponent(kalpproblemi))
                                            .addGap(33, 33, 33)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(hepatit, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tüberkiloz, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(diyabet, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(sarılık, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(24, 24, 24)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(epilepsi)
                                                .addComponent(artrit)
                                                .addComponent(astım)
                                                .addComponent(anemi)))
                                        .addComponent(jLabel18)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel8))
                                            .addGap(23, 23, 23)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(akrabaadresalanı, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                                                .addComponent(yakınakrabatelalanı, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(kiloalanı, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(boyalanı, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                                .addComponent(isimalanı, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(tarihalanı, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(adresalanı, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                                                .addComponent(telno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                                                .addComponent(doğumtarihialanı, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                                                .addComponent(medenidurumalanı, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))))
                                    .addGap(328, 328, 328))
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jRadioButton1)
                        .addGap(54, 54, 54)
                        .addComponent(jRadioButton2)))
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tarihalanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(isimalanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(adresalanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(telno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(doğumtarihialanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(medenidurumalanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(yakınakrabatelalanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(akrabaadresalanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton6)
                                    .addComponent(jRadioButton5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(kiloalanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton11)
                            .addComponent(jRadioButton12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sarılık)
                            .addComponent(anemi)
                            .addComponent(kalpproblemi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kalpteüfürüm)
                            .addComponent(hepatit)
                            .addComponent(astım))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(romatizma)
                            .addComponent(diyabet)
                            .addComponent(artrit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sinüsproblemi)
                            .addComponent(tüberkiloz)
                            .addComponent(epilepsi))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton13)
                            .addComponent(jRadioButton14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton15)
                            .addComponent(jRadioButton16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton17)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton18)
                                .addComponent(jButton1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boyalanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresalanı;
    private javax.swing.JTextField akrabaadresalanı;
    private javax.swing.JCheckBox anemi;
    private javax.swing.JCheckBox artrit;
    private javax.swing.JCheckBox astım;
    private javax.swing.JTextField boyalanı;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBox diyabet;
    private javax.swing.JTextField doğumtarihialanı;
    private javax.swing.JCheckBox epilepsi;
    private javax.swing.JCheckBox hepatit;
    private javax.swing.JTextField isimalanı;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox kalpproblemi;
    private javax.swing.JCheckBox kalpteüfürüm;
    private javax.swing.JTextField kiloalanı;
    private javax.swing.JTextField medenidurumalanı;
    private javax.swing.JCheckBox romatizma;
    private javax.swing.JCheckBox sarılık;
    private javax.swing.JCheckBox sinüsproblemi;
    private javax.swing.JTextField tarihalanı;
    private javax.swing.JTextField telno;
    private javax.swing.JCheckBox tüberkiloz;
    private javax.swing.JTextField yakınakrabatelalanı;
    // End of variables declaration//GEN-END:variables
}
